default: &default
  encoding: utf8
  adapter: postgresql
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 50)), Integer(ENV.fetch("DB_POOL", 50))].max %>
  timeout: 5000
  #  Make sure you've created a database account for the AACT_DB_SUPER_USERNAME (default: aact) with permission to create databases.
  #  Also, add an entry for this user in the .pgpass file in the root directory of the user who run the rails apps so the app knows its password.
  username: <%= ENV.fetch("AACT_DB_SUPER_USERNAME", 'aact') %>

development:
  <<: *default
  host:  <%= ENV.fetch('APPLICATION_HOST', 'localhost') %>
  database: <%= ENV.fetch('AACT_BACK_DATABASE_NAME', 'aact') %>
  password: <%= ENV.fetch("AACT_PASSWORD", '') %>
  pool: 50

test:
  <<: *default
  host:  <%= ENV.fetch('APPLICATION_HOST', 'localhost') %>
  password: <%= ENV.fetch("AACT_PASSWORD", '') %>
  database: aact_test

production:
  <<: *default
  username: <%= ENV.fetch("AACT_DB_SUPER_USERNAME", 'aact') %>
  password: <%= ENV.fetch("AACT_PASSWORD", '') %>
  host:  <%= ENV.fetch('AACT_HOST', 'localhost') %>
  database: <%= ENV.fetch('AACT_BACK_DATABASE_NAME', 'aact') %>

public:
  <<: *default
  host:  <%= ENV.fetch('AACT_PUBLIC_HOSTNAME', 'localhost') %>
  database: <%= ENV.fetch('AACT_PUBLIC_DATABASE_NAME', 'aact_pub') %>


